// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;

namespace HospitalManagementSystem2.Models;

public partial class Appointment
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int StaffId { get; set; }

    public int DepartmentId { get; set; }

    public DateTime AppointmentDateTime { get; set; }

    public string Status { get; set; }

   // public virtual MedicalHistory MedicalHistory { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual Department Department { get; set; }

}