// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


using System;
using System.Collections.Generic;

namespace HospitalManagementSystem2.Models;

public partial class MedicalHistory
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int StaffId { get; set; }

    public string Diagnosis { get; set; }

    public string TreatmentPlan { get; set; }

    public string Prescription { get; set; }

    public DateOnly VisitedDate { get; set; }

   // public int AppointmentId { get; set; }

   // public virtual ICollection<Appointment> Appointments { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual Patient Patient { get; set; }
}