// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using HospitalManagementSystem2.Models;
using System;
using System.Collections.Generic;

namespace HospitalManagementSystem2.Models;

public partial class Patient
{
    public int Id { get; set; }

    public string Address { get; set; }

    public DateOnly Dob { get; set; }

    public string EmergencyContact { get; set; }

    public string InsuranceProvider { get; set; }

    public string InsuranceNumber { get; set; }

    public int UserId { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<MedicalHistory> MedicalHistories { get; set; } = new List<MedicalHistory>();

    public virtual User User { get; set; }
}