// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HospitalManagementSystem2.Models;

public partial class Staff
{
    public int Id { get; set; }

    public string Position { get; set; }

    public string Qualification { get; set; }

    public int UserId { get; set; }

    public int DepartmentId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<StaffSchedule> StaffSchedules { get; set; } = new List<StaffSchedule>();

    public virtual User User { get; set; }
}