// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HospitalManagementSystem2.Models;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public int RoleId { get; set; }

    public bool IsDeleted {  get; set; }

    public virtual Role Role { get; set; }

    public virtual  Staff Staff{ get; set; }
}